---
kind: pipeline
name: Build

steps:
  - name: Build image
    image: docker
    commands:
      - docker build -t pvnovarese/clock:test-1 .
      - syft pvnovarese/clock:test-1
      - grype pvnovarese/clock:test-1
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: toolbox
        path: /toolbox

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: toolbox
    host:
      path: /usr/local/bin
