---
kind: pipeline
name: Build

steps:
  - name: Build image
    image: docker
    commands:
      - docker build -t pvnovarese/clock:test-1 .
      - /usr/local/bin/syft pvnovarese/clock:test-1
      - /usr/local/bin/grype pvnovarese/clock:test-1
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: user_local_bin
        path: /usr/local/bin

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: usr_local_bin
    host:
      path: /usr/local/bin
