---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t pvnovarese/clock:test-1
