---
kind: pipeline
name: Build

trigger:
  branch:
  - main
  event:
  - push

steps:
  - name: Build image
    image: docker
    environment:
      PASSWORD:
        from_secret: hub_password
    commands:
      # set the image name/tag:  
      # old version: DRONE_REPO:$DRONE_BUILD_NUMBER
      # note that in this case $DRONE_REPO only works because my github username and my docker hub username are the same
      - IMAGE="${DRONE_REPO}:${DRONE_BRANCH}-dev"
      - docker build -t $${IMAGE} .
      # need to update this docker login 
      - docker login -u $$DRONE_REPO_NAMESPACE -p $PASSWORD
      - docker push $${IMAGE}
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
        
  - name: Scan image
    # using my anchore-tools until anchorectl 1.0.0 ships
    image: docker.io/pvnovarese/anchore-tools:main
    environment: 
      ANCHORECTL_USERNAME:
        from_secret: anchorectl_username
      ANCHORECTL_PASSWORD:
        from_secret: anchorectl_password
      ANCHORECTL_URL:
        from_secret: anchorectl_url
    commands:
      - IMAGE="${DRONE_REPO}:${DRONE_BRANCH}-dev"
      # add image to queue, pass actual dockerfile, then wait for results
      - anchorectl image add --force --no-auto-subscribe --wait --annotation build_tool=drone --dockerfile ./Dockerfile $${IMAGE}
      # check evaluation and break the pipeline if the result is FAIL/STOP
      - anchorectl image check --fail-based-on-results --detail $${IMAGE}
      #
      # older anchore-cli commands (this is deprecated but might be useful for troubleshooting)
      #- anchore-cli image add $DRONE_REPO:$DRONE_BUILD_NUMBER 
      #- anchore-cli image wait $DRONE_REPO:$DRONE_BUILD_NUMBER 
      #- anchore-cli evaluate check $DRONE_REPO:$DRONE_BUILD_NUMBER
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
        
  - name: Promote image
    image: docker
    environment:
      PASSWORD:
        from_secret: hub_password
    commands:
      - IMAGE="${DRONE_REPO}:${DRONE_BRANCH}-dev"
      - IMAGE_PROD="${DRONE_REPO}:${DRONE_BRANCH}"
      - docker login -u $$DRONE_REPO_NAMESPACE -p $PASSWORD
      - docker tag $${IMAGE} $${IMAGE_PROD}
      - docker push $${IMAGE_PROD}
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
        
  - name: Scan Promoted Image
    # using my anchore-tools until anchorectl 1.0.0 ships
    image: docker.io/pvnovarese/anchore-tools:main
    environment: 
      ANCHORECTL_USERNAME:
        from_secret: anchorectl_username
      ANCHORECTL_PASSWORD:
        from_secret: anchorectl_password
      ANCHORECTL_URL:
        from_secret: anchorectl_url
    commands:
      - IMAGE_PROD="${DRONE_REPO}:${DRONE_BRANCH}"
      # add image to queue, pass actual dockerfile
      # this time we don't need to wait for the scan to complete and we don't need to check the result
      # just add the image to the queue and move on
      - anchorectl image add --force --no-auto-subscribe --annotation build_tool=drone --dockerfile ./Dockerfile $${IMAGE_PROD}
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
        
  - name: Cleanup
    image: docker
    commands:
      - IMAGE="${DRONE_REPO}:${DRONE_BRANCH}-dev"
      - IMAGE_PROD="{DRONE_REPO}:${DRONE_BRANCH}"
      - docker image rm $${IMAGE} $${IMAGE_PROD}
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
