---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build -t pvnovarese/clock:test-1 .
- name: scan
  commands:
  - syft pvnovarese/clock:test-1
  - grype pvnovarese/clock:test-1
- name: push
  commands:
  - echo "do a docker push here once we figure out how to use secrets with drone"
